import React from 'react'
import PropTypes from 'prop-types'

const rNJVN = props => {
    return (
        <div>
            
        </div>
    )
}

rNJVN.propTypes = {
  {/* <div class="row-col">
            <img
              src="https://images.unsplash.com/photo-1562322140-8baeececf3df?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2Fsb258ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80"
              width="300"
            />
            <div class="layer">
              <h3>SALON</h3>
            </div>
          </div> */}
          {/* <div class="row-col">
            <img
              src="https://media.istockphoto.com/photos/woman-at-home-calling-a-plumber-about-a-leaking-pipe-in-her-sink-picture-id1300212975?b=1&k=20&m=1300212975&s=170667a&w=0&h=IX7i5mCBiHoOX6UA9hqODeNhKRFEAhI12rhLbx5NYoM="
              width="300"
            />
            <div class="layer">
              <h3>PLUMBER</h3>
            </div>
          </div> */}
          {/* <div class="row-col"> */}
            {/* <img
              src="https://media.istockphoto.com/photos/hardworking-woman-driving-car-for-rideshare-picture-id1247754273?b=1&k=20&m=1247754273&s=170667a&w=0&h=Cywy2UNeEqun-DI5AGPYraYOxIvQoBurdyJgZh2BSk8="
              width="300"
            /> */}
            {/* <div class="layer">
              <h3>ACTING DRIVER</h3>
            </div>
          </div> */}
          {/* <div class="row-col">
            <img
              src="https://images.unsplash.com/photo-1518181835702-6eef8b4b2113?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGVsZWN0cmljaWFufGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80"
              width="300"
            />
            <div class="layer">
              <h3>ELECTRICIAN</h3>
            </div>
          </div> */}
}
  {/* <section class="workers">
        <h1>Service workers</h1>
        <p>
          Urban Company is an Indian gig marketplace that offers home
          installation, maintenance and repair services, and home beauty and
          wellness services
        </p>
        <div className="service">
          <div class="service-workers">
            <h1>electrician</h1>
            <p>
              There are also many advantages to this career. In addition to
              these benefits, electricians can take satisfaction in playing an
              important role in their communities. Without their wiring work,
              the world might not be as comfortable of a place
            </p>
          </div>
          <div class="service-workers">
            <h1>Saloon</h1>
            <p>
              Do salons do men's hair? The main difference between the two types
              of haircutters is that barbers are typically trained to cut
              shorter, traditional haircuts for men while salon stylists are
              trained to cut longer, fuller men's styles. A barber's primary
              focus is cutting men's hair.
            </p>
          </div>
          <div class="service-workers">
            <h1>Acting Driver</h1>
            <p>
              Drivers increasingly opt to freelance rather than become full-time
              chauffeurs. Increasingly, young drivers, some in their early 20s
              and others in their 30s are now willing to risk an unstable income
              and prefer to be freelancers. Popularly known as 'acting drivers
              ', they choose to drive based on the customer's demands
            </p>
          </div>
        </div>
      </section> */}
export default rNJVN
