export let SET_ALERT = "SET_ALERT"
export let REMOVE_ALERT = "REMOVE_ALERT"
export let REGISTER_SUCCESS = "REGISTER_SUCCESS"
export let REGISTER_FAILURE = "REGISTER_FAILURE"
export let LOGIN_SUCCESS = "LOGIN_SUCCESS"
export let LOGIN_FAILURE = "LOGIN_FAILURE"
export let AUTH_ERROR = "AUTH_ERROR"
export let USER_LOADED = "USER_LOADED"
export let GET_PROFILE = "GET_PROFILE"
export let PROFILE_ERROR = "PROFILE_ERROR"
export let GET_ALLPROFILE = "GET_ALLPROFILE"
export let ALLPROFILE_ERROR = "ALLPROFILE_ERROR"


